# Generated by Django 6.0.7 on 2026-08-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatspp", "0003_alter_sitesetting_site_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="site_address",
            field=models.TextField(
                default="Shekhah Wala Bazar, Nazad HabibBank, Farooqabad, Pakistan"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_email",
            field=models.EmailField(
                default="info@tahirrafiqueclothehouse.com",
                help_text="Email address for contact form submissions",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_name",
            field=models.CharField(
                default="Tahir Rafique Clothe House",
                help_text="Name of the site",
                max_length=100,
            ),
        ),
    ]
