# Generated by Django 6.0.7 on 2026-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session key for guest users",
                max_length=255,
                null=True,
            ),
        ),
    ]
